spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/nagendra
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
plan-api:
  messages:
    planSaveSucc: Plan Saved Successfully
    planSaveFail: Plan Saved Failed
    planUpdateSucc: Plan Updated Sucessfully
    planUpdateFail: Plan Update Failed
    planDeleteSucc: Plan Deleted Sucessfully
    planDeleteFail: Plan Delete Failed
    planStatusChange: Plan Status Deleted Sucessfully
    planStatusChangeFail: Plan Status CHange Failed 